#毋庸置疑,我从塔克小车顺手抄的
version: holy_shit_version
port_name: /dev/ttyTHS1 #设备端口
baud_rate: 115200       #通信波特率，固定115200

odom_frame: odom               #里程计坐标系
base_frame: base_link      #底盘坐标系
imu_frame: imu_link        #IMU坐标系

servo_bias:   0                #舵机偏差修正量
linear_correction_factor: 1.00  #线速度校准系数

publish_odom_transform: True   #是否发布odom->base_footprint坐标变换
Kp: 0.017                         #OpenCRP电机控制PID，P参数
Ki: 0                           #OpenCRP电机控制PID, I参数
Kd: 0.2                         #OpenCRP电机控制PID，D参数
servo_angle:  0                 #舵机角度,左负右正

control_rate: 30                #底盘控制频率  
